name: cil
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - zlib
  - zeromq
  - asttokens
  - bzip2
  - jupyter_core
  - ipython
  - nest-asyncio
  - libcxx
  - psutil
  - backports
  - matplotlib-inline
  - ptyprocess
  - python-dateutil
  - entrypoints
  - pickleshare
  - debugpy
  - xz
  - ncurses
  - tornado
  - readline
  - appnope
  - prompt-toolkit
  - stack_data
  - backcall
  - wcwidth
  - backports.functools_lru_cache
  - executing
  - pyzmq
  - setuptools
  - libffi
  - pip
  - jupyter_client
  - wheel
  - pexpect
  - six
  - jedi
  - openssl
  - pygments
  - decorator
  - libsodium
  - parso
  - python_abi
  - ca-certificates
  - tk
  - pure_eval
  - libzlib
  - traitlets
  - sqlite
  - pyparsing
  - packaging
  - ipykernel
  - scipy
  - scikit-learn
  - tqdm
  - matplotlib