# Wa&B Sweep
project: cil-lab-lightgcn
program: main.py
method: random

metric:
  name: eval_loss
  goal: minimize

parameters:
  # model architecture
  num_layers:
    values: [3,4,5]
  emb_size:
    values: [32, 64, 128, 256]

  # training hyperparams
  epochs:
    value: 20
  learning_rate:
    distribution: uniform
    min: 0.000
    max: 0.002
  batch_size:
    values: [1024, 2048, 4096]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - '--wandb'
  - 'online'
  - '--save'
  - False
  - ${args}