# Wa&B Sweep
project: cil-lab
program: main.py
method: bayes

metric:
  name: val_RMSE
  goal: minimize

parameters:
  # model architecture
  major:
    value: users
  activation:
    values: [selu, elu, swish]
  layer1_dim:
    values: [32, 64, 128, 256, 512, 1024]
  layer2_dim:
    values: [32, 64, 128, 256, 512, 1024]
  layer3_dim:
    values: [32, 64, 128, 256, 512, 1024]

  # training hyperparams
  epochs:
    value: 20
  optimizer:
    values: [adagrad, momentum]
  learning_rate:
    values: [0.001, 0.005, 0.01]
  batch_size:
    value: 128

  # regularization params
  weight_decay:
    values: [0, 0.0001, 0.0005, 0.001]
  dropout:
    values: [0.2, 0.4, 0.6, 0.8]
  noise_prob:
    value: 0
  dense_refeeding_steps:
    value: 2